### ISSUE TITLE
Tiqr config doesn\'t use UserSecretStorage during registration

### ISSUE THREAD

**Issue by phavekes** [OpenConext/Stepup-tiqr#282]
[This issue is imported from pivotal - Originaly created at Jan 24, 2022 by Peter Havekes](https://www.pivotaltracker.com/story/show/181010869)

If a different location for storing the secrets is specified in parameters.yaml, this location is only used during authentication. During registration, the UserStorage is used instead of UserSecretStorage.

Example config:
```
        storage:
            statestorage:
              type: \'memcache\'
              arguments:
                prefix: \'tiqr_\'
                servers:
                  - host: \'145.x.y.z\'
            devicestorage:
              type: \'tokenexchange\'
              arguments:
                url: \'https://tokenexchange/\'
                appid: \'tiqr\'
            userstorage:
              type: \'pdo\'
              arguments:
                table: \'user\'
                dsn: \'mysql:host=145.x.y.z;dbname=tiqr\'
                username: \'tiqr\'
                password: \'xxxxxxxxx\'
            usersecretstorage:
              type: \'oathserviceclient\'
              arguments:
                apiURL: \'https://keyserver\'
                consumerKey: \'xxxxxx\'

```

Thanks to a short peer debug session between Peter and Michiel, we found out that the TiqrFactory does not actually distinguishes between `userstorage` and `usersecretstorage`. It always builds the userstorage connection for both the secrets and regular user storage options.

The factory method should be made aware for what context the repository is being created. This might require the creation of a new factory method, or a new repository class. As it will probably be hard to have knowledge of this context during construction time. A good debug session should give more insights into this problem.

A suggestion is to configure the `userstorage` with `pdo` while the `usersecretstorage` is configured with `file` storage. That should reproduce the problem in a dev environment without having to configure the `oathserviceclient`.
